apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: feedscommand
  name: feedscommand
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: feedscommand
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: feedscommand
    spec:
      containers:
        - args:
            - command-service
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: JWT_SECRET
            - name: NATS_ADDRESS
              value: nats:4222
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: POSTGRES_USER
          image: registry.digitalocean.com/shawarma/cqrs
          name: cqrs-command
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
