apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: usersquery
  name: usersquery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usersquery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: usersquery
    spec:
      containers:
        - args:
            - users-query
          env:
            - name: JWT_SECRET
            - name: MEMCACHED_ADDRESS
              value: memcached:11211
            - name: NATS_ADDRESS
              value: nats:4222
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: usersquery
          name: cqrs-users-query
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
